In [2]:
import numpy as np


In [3]:
arr1=np.zeros((1,6))
arr1

array([[0., 0., 0., 0., 0., 0.]])

In [4]:
arr1=np.delete(arr1,5)
arr1

array([0., 0., 0., 0., 0.])

In [5]:
arr1=np.append(arr1,9)
arr1

array([0., 0., 0., 0., 0., 9.])

In [9]:
arr1[5]=9


In [10]:
print(arr1)

[0. 0. 0. 0. 0. 9.]
